# Generated by Django 5.0.1 on 2024-02-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('pincode', models.BigIntegerField()),
                ('hotel_ref_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Hotel_table',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('State', models.CharField(blank=True, max_length=50)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('DistanceFromHotel', models.IntegerField(blank=True)),
                ('TypeofAttraction', models.CharField(blank=True, choices=[('historical sites', 'historical sites'), ('natural landmarks', 'natural landmarks'), ('museums', 'museums'), ('recreational activities', 'recreational activities')], max_length=50)),
                ('OperatingHours', models.IntegerField(blank=True)),
                ('LocalDiningPrivision', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'db_table': 'Place_table',
            },
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'provider_table',
            },
        ),
        migrations.CreateModel(
            name='ProvPlaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('State', models.CharField(blank=True, max_length=50)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('DistanceFromHotel', models.IntegerField(blank=True)),
                ('TypeofAttraction', models.CharField(blank=True, choices=[('historical sites', 'historical sites'), ('natural landmarks', 'natural landmarks'), ('museums', 'museums'), ('recreational activities', 'recreational activities')], max_length=50)),
                ('OperatingHours', models.IntegerField(blank=True)),
                ('LocalDiningPrivision', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'db_table': 'ProvPlace_table',
            },
        ),
        migrations.CreateModel(
            name='Provservices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NameofHotel', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('hotelRefId', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('AccomodationType', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suites', 'Suites')], max_length=50)),
                ('Amenities', models.CharField(max_length=80)),
                ('RoomNo', models.IntegerField()),
                ('RoomSize', models.CharField(max_length=50)),
                ('RoomType', models.CharField(max_length=60)),
                ('CostPerNight', models.IntegerField()),
                ('CheckInandCheckOutPolicies', models.CharField(blank=True, max_length=100)),
                ('Diningtype', models.CharField(choices=[('FineDine', 'FineDine'), ('CasualDine', 'CasualDine'), ('Buffet', 'Buffet'), ('Bestro', 'Bestro')], max_length=60)),
                ('diningTimings', models.CharField(max_length=60)),
                ('BarandBeverageservice', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=60)),
                ('privateDining', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=60)),
                ('LiveEntertainment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=60)),
            ],
            options={
                'db_table': 'Provservice_table',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=10)),
                ('Qualification', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('mobileNumber', models.BigIntegerField()),
                ('EnterRequiredUsername', models.CharField(max_length=30)),
                ('EnterPassword', models.CharField(max_length=30)),
                ('ConfirmPassword', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'provRegister_table',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NameofHotel', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('hotelRefId', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('AccomodationType', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suites', 'Suites')], max_length=50)),
                ('Amenities', models.CharField(max_length=80)),
                ('RoomNo', models.IntegerField()),
                ('RoomSize', models.CharField(max_length=50)),
                ('RoomType', models.CharField(max_length=60)),
                ('CostPerNight', models.IntegerField()),
                ('CheckInandCheckOutPolicies', models.CharField(blank=True, max_length=100)),
                ('Diningtype', models.CharField(choices=[('FineDine', 'FineDine'), ('CasualDine', 'CasualDine'), ('Buffet', 'Buffet'), ('Bestro', 'Bestro')], max_length=60)),
                ('diningTimings', models.CharField(max_length=60)),
                ('BarandBeverageservice', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=60)),
                ('privateDining', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=60)),
                ('LiveEntertainment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=60)),
            ],
            options={
                'db_table': 'Service_table',
            },
        ),
    ]
