# Generated by Django 5.0 on 2024-03-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Email',
            field=models.CharField(max_length=255),
        ),
    ]
